-- schema.sql - Tales of Time database schema
-- Run once to create all tables: python database/init_db.py

PRAGMA foreign_keys = ON;

-- ── Lookup tables ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS CharacterClass (
	ClassID		INTEGER PRIMARY KEY AUTOINCREMENT,
	ClassName	VARCHAR(50)	 NOT NULL UNIQUE,
	Description	TEXT
);

CREATE TABLE IF NOT EXISTS Species (
	SpeciesID	INTEGER PRIMARY KEY AUTOINCREMENT,
	SpeciesName	VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Alignment (
	AlignmentID	  INTEGER PRIMARY KEY AUTOINCREMENT,
	AlignmentName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ItemType (
	ItemTypeID INTEGER PRIMARY KEY AUTOINCREMENT,
	TypeName   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Rarity (
	RarityID   INTEGER PRIMARY KEY AUTOINCREMENT,
	RarityName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Region (
	RegionID   INTEGER PRIMARY KEY AUTOINCREMENT,
	RegionName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Difficulty (
	DifficultyID   INTEGER PRIMARY KEY AUTOINCREMENT,
	DifficultyName VARCHAR(50) NOT NULL UNIQUE
);

-- ── Core entities ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS Character (
	CharacterID   INTEGER PRIMARY KEY AUTOINCREMENT,
	CharacterName VARCHAR(100) NOT NULL,
	ClassID		  INTEGER NOT NULL REFERENCES CharacterClass(ClassID) ON DELETE CASCADE,
	SpeciesID	  INTEGER NOT NULL REFERENCES Species(SpeciesID) ON DELETE CASCADE,
	AlignmentID	  INTEGER NOT NULL REFERENCES Alignment(AlignmentID) ON DELETE CASCADE,
	Level		  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Item (
	ItemID	   INTEGER PRIMARY KEY AUTOINCREMENT,
	ItemName   VARCHAR(100) NOT NULL,
	ItemTypeID INTEGER NOT NULL REFERENCES ItemType(ItemTypeID) ON DELETE CASCADE,
	RarityID   INTEGER NOT NULL REFERENCES Rarity(RarityID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Quest (
	QuestID		 INTEGER PRIMARY KEY AUTOINCREMENT,
	QuestName	 VARCHAR(100) NOT NULL,
	RegionID	 INTEGER NOT NULL REFERENCES Region(RegionID) ON DELETE CASCADE,
	DifficultyID INTEGER NOT NULL REFERENCES Difficulty(DifficultyID) ON DELETE CASCADE
);

-- ── Join tables ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS Inventory (
	InventoryID INTEGER PRIMARY KEY AUTOINCREMENT,
	CharacterID INTEGER NOT NULL REFERENCES Character(CharacterID) ON DELETE CASCADE,
	ItemID		INTEGER NOT NULL REFERENCES Item(ItemID) ON DELETE CASCADE,
	Quantity	INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS CharacterQuest (
	CharacterQuestID INTEGER PRIMARY KEY AUTOINCREMENT,
	CharacterID		 INTEGER NOT NULL REFERENCES Character(CharacterID) ON DELETE CASCADE,
	QuestID			 INTEGER NOT NULL REFERENCES Quest(QuestID) ON DELETE CASCADE,
	CompletionDate	 DATETIME NULL
);
